<?php
$MZ700FON = array(
    array('code'=> 0x000, 'patterns' => array( '........', '........', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x001, 'patterns' => array( '...oo...', '..o..o..', '.o....o.', '.oooooo.', '.o....o.', '.o....o.', '.o....o.', '........')),
    array('code'=> 0x002, 'patterns' => array( '.ooooo..', '..o...o.', '..o...o.', '..oooo..', '..o...o.', '..o...o.', '.ooooo..', '........')),
    array('code'=> 0x003, 'patterns' => array( '...ooo..', '..o...o.', '.o......', '.o......', '.o......', '..o...o.', '...ooo..', '........')),
    array('code'=> 0x004, 'patterns' => array( '.oooo...', '..o..o..', '..o...o.', '..o...o.', '..o...o.', '..o..o..', '.oooo...', '........')),
    array('code'=> 0x005, 'patterns' => array( '.oooooo.', '.o......', '.o......', '.oooo...', '.o......', '.o......', '.oooooo.', '........')),
    array('code'=> 0x006, 'patterns' => array( '.oooooo.', '.o......', '.o......', '.oooo...', '.o......', '.o......', '.o......', '........')),
    array('code'=> 0x007, 'patterns' => array( '...ooo..', '..o...o.', '.o......', '.o..ooo.', '.o....o.', '..o...o.', '...ooo..', '........')),
    array('code'=> 0x008, 'patterns' => array( '.o....o.', '.o....o.', '.o....o.', '.oooooo.', '.o....o.', '.o....o.', '.o....o.', '........')),
    array('code'=> 0x009, 'patterns' => array( '...ooo..', '....o...', '....o...', '....o...', '....o...', '....o...', '...ooo..', '........')),
    array('code'=> 0x00a, 'patterns' => array( '....ooo.', '.....o..', '.....o..', '.....o..', '.....o..', '.o...o..', '..ooo...', '........')),
    array('code'=> 0x00b, 'patterns' => array( '.o....o.', '.o...o..', '.o..o...', '.ooo....', '.o..o...', '.o...o..', '.o....o.', '........')),
    array('code'=> 0x00c, 'patterns' => array( '.o......', '.o......', '.o......', '.o......', '.o......', '.o......', '.oooooo.', '........')),
    array('code'=> 0x00d, 'patterns' => array( '.o....o.', '.oo..oo.', '.o.oo.o.', '.o.oo.o.', '.o....o.', '.o....o.', '.o....o.', '........')),
    array('code'=> 0x00e, 'patterns' => array( '.o....o.', '.oo...o.', '.o.o..o.', '.o..o.o.', '.o...oo.', '.o....o.', '.o....o.', '........')),
    array('code'=> 0x00f, 'patterns' => array( '...oo...', '..o..o..', '.o....o.', '.o....o.', '.o....o.', '..o..o..', '...oo...', '........')),
    array('code'=> 0x010, 'patterns' => array( '.ooooo..', '.o....o.', '.o....o.', '.ooooo..', '.o......', '.o......', '.o......', '........')),
    array('code'=> 0x011, 'patterns' => array( '...oo...', '..o..o..', '.o....o.', '.o....o.', '.o..o.o.', '..o..o..', '...oo.o.', '........')),
    array('code'=> 0x012, 'patterns' => array( '.ooooo..', '.o....o.', '.o....o.', '.ooooo..', '.o..o...', '.o...o..', '.o....o.', '........')),
    array('code'=> 0x013, 'patterns' => array( '..oooo..', '.o....o.', '.o......', '..oooo..', '......o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x014, 'patterns' => array( '..ooooo.', '....o...', '....o...', '....o...', '....o...', '....o...', '....o...', '........')),
    array('code'=> 0x015, 'patterns' => array( '.o....o.', '.o....o.', '.o....o.', '.o....o.', '.o....o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x016, 'patterns' => array( '.o....o.', '.o....o.', '.o....o.', '..o..o..', '..o..o..', '...oo...', '...oo...', '........')),
    array('code'=> 0x017, 'patterns' => array( '.o....o.', '.o....o.', '.o....o.', '.o.oo.o.', '.o.oo.o.', '.oo..oo.', '.o....o.', '........')),
    array('code'=> 0x018, 'patterns' => array( '.o....o.', '.o....o.', '..o..o..', '...oo...', '..o..o..', '.o....o.', '.o....o.', '........')),
    array('code'=> 0x019, 'patterns' => array( '..o...o.', '..o...o.', '..o...o.', '...ooo..', '....o...', '....o...', '....o...', '........')),
    array('code'=> 0x01a, 'patterns' => array( '.oooooo.', '......o.', '.....o..', '...oo...', '..o.....', '.o......', '.oooooo.', '........')),
    array('code'=> 0x01b, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', 'oooooooo', '....o...', '....o...', '....o...')),
    array('code'=> 0x01c, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', '....oooo', '........', '........', '........')),
    array('code'=> 0x01d, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', 'ooooo...', '........', '........', '........')),
    array('code'=> 0x01e, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', '....oooo', '....o...', '....o...', '....o...')),
    array('code'=> 0x01f, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', 'oooooooo', '........', '........', '........')),
    array('code'=> 0x020, 'patterns' => array( '..oooo..', '.o....o.', '.o...oo.', '.o.oo.o.', '.oo...o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x021, 'patterns' => array( '....o...', '...oo...', '..o.o...', '....o...', '....o...', '....o...', '..ooooo.', '........')),
    array('code'=> 0x022, 'patterns' => array( '..oooo..', '.o....o.', '......o.', '....oo..', '..oo....', '.o......', '.oooooo.', '........')),
    array('code'=> 0x023, 'patterns' => array( '..oooo..', '.o....o.', '......o.', '..oooo..', '......o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x024, 'patterns' => array( '.....o..', '....oo..', '...o.o..', '..o..o..', '.oooooo.', '.....o..', '.....o..', '........')),
    array('code'=> 0x025, 'patterns' => array( '.oooooo.', '.o......', '.oooo...', '.....o..', '......o.', '.o...o..', '..ooo...', '........')),
    array('code'=> 0x026, 'patterns' => array( '...ooo..', '..o.....', '.o......', '.ooooo..', '.o....o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x027, 'patterns' => array( '.oooooo.', '.o....o.', '.....o..', '....o...', '...o....', '...o....', '...o....', '........')),
    array('code'=> 0x028, 'patterns' => array( '..oooo..', '.o....o.', '.o....o.', '..oooo..', '.o....o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x029, 'patterns' => array( '..oooo..', '.o....o.', '.o....o.', '..ooooo.', '......o.', '.....o..', '..ooo...', '........')),
    array('code'=> 0x02a, 'patterns' => array( '........', '........', '........', '.oooooo.', '........', '........', '........', '........')),
    array('code'=> 0x02b, 'patterns' => array( '........', '........', '.oooooo.', '........', '.oooooo.', '........', '........', '........')),
    array('code'=> 0x02c, 'patterns' => array( '........', '........', '....o...', '........', '........', '....o...', '....o...', '...o....')),
    array('code'=> 0x02d, 'patterns' => array( '........', '......o.', '.....o..', '....o...', '...o....', '..o.....', '.o......', '........')),
    array('code'=> 0x02e, 'patterns' => array( '........', '........', '........', '........', '........', '...oo...', '...oo...', '........')),
    array('code'=> 0x02f, 'patterns' => array( '........', '........', '........', '........', '........', '....o...', '....o...', '...o....')),
    array('code'=> 0x030, 'patterns' => array( '........', 'oooooooo', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x031, 'patterns' => array( '.o......', '.o......', '.o......', '.o......', '.o......', '.o......', '.o......', '.o......')),
    array('code'=> 0x032, 'patterns' => array( 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'oooooooo')),
    array('code'=> 0x033, 'patterns' => array( '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', 'oooooooo')),
    array('code'=> 0x034, 'patterns' => array( '........', '........', '........', 'oooooooo', '........', '........', '........', '........')),
    array('code'=> 0x035, 'patterns' => array( '...o....', '...o....', '...o....', '...o....', '...o....', '...o....', '...o....', '...o....')),
    array('code'=> 0x036, 'patterns' => array( 'oooooooo', 'oooooooo', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x037, 'patterns' => array( 'oo......', 'oo......', 'oo......', 'oo......', 'oo......', 'oo......', 'oo......', 'oo......')),
    array('code'=> 0x038, 'patterns' => array( '........', '........', '........', '........', '........', 'oooooooo', '........', '........')),
    array('code'=> 0x039, 'patterns' => array( '.....o..', '.....o..', '.....o..', '.....o..', '.....o..', '.....o..', '.....o..', '.....o..')),
    array('code'=> 0x03a, 'patterns' => array( '........', '........', '........', '........', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo')),
    array('code'=> 0x03b, 'patterns' => array( '....oooo', '....oooo', '....oooo', '....oooo', '....oooo', '....oooo', '....oooo', '....oooo')),
    array('code'=> 0x03c, 'patterns' => array( '........', '........', '........', '........', '........', '........', '........', 'oooooooo')),
    array('code'=> 0x03d, 'patterns' => array( '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o')),
    array('code'=> 0x03e, 'patterns' => array( '........', '........', '........', '........', '........', '........', 'oooooooo', 'oooooooo')),
    array('code'=> 0x03f, 'patterns' => array( '......oo', '......oo', '......oo', '......oo', '......oo', '......oo', '......oo', '......oo')),
    array('code'=> 0x040, 'patterns' => array( '........', '........', '....o...', '.....o..', 'ooooooo.', '.....o..', '....o...', '........')),
    array('code'=> 0x041, 'patterns' => array( '....o...', '...ooo..', '..ooooo.', '.ooooooo', '.ooooooo', '...ooo..', '..ooooo.', '........')),
    array('code'=> 0x042, 'patterns' => array( 'oooooooo', '.ooooooo', '..oooooo', '...ooooo', '....oooo', '.....ooo', '......oo', '.......o')),
    array('code'=> 0x043, 'patterns' => array( 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo')),
    array('code'=> 0x044, 'patterns' => array( '....o...', '...ooo..', '..ooooo.', '.ooooooo', '..ooooo.', '...ooo..', '....o...', '........')),
    array('code'=> 0x045, 'patterns' => array( '........', '........', '...o....', '..o.....', '.ooooooo', '..o.....', '...o....', '........')),
    array('code'=> 0x046, 'patterns' => array( '....o...', '...ooo..', '..o.o.o.', '.ooooooo', '..o.o.o.', '....o...', '....o...', '........')),
    array('code'=> 0x047, 'patterns' => array( '........', '..oooo..', '.oooooo.', '.oooooo.', '.oooooo.', '.oooooo.', '..oooo..', '........')),
    array('code'=> 0x048, 'patterns' => array( '........', '..oooo..', '.o....o.', '.o....o.', '.o....o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x049, 'patterns' => array( '..oooo..', '.o....o.', '......o.', '....oo..', '...o....', '........', '...o....', '........')),
    array('code'=> 0x04a, 'patterns' => array( 'oooooooo', 'oo....oo', 'o......o', 'o......o', 'o......o', 'o......o', 'oo....oo', 'oooooooo')),
    array('code'=> 0x04b, 'patterns' => array( '........', '........', '........', '........', '......oo', '.....o..', '....o...', '....o...')),
    array('code'=> 0x04c, 'patterns' => array( '........', '........', '........', '........', 'oo......', '..o.....', '...o....', '...o....')),
    array('code'=> 0x04d, 'patterns' => array( 'o.......', 'oo......', 'ooo.....', 'oooo....', 'ooooo...', 'oooooo..', 'ooooooo.', 'oooooooo')),
    array('code'=> 0x04e, 'patterns' => array( '.......o', '......oo', '.....ooo', '....oooo', '...ooooo', '..oooooo', '.ooooooo', 'oooooooo')),
    array('code'=> 0x04f, 'patterns' => array( '........', '........', '....o...', '........', '........', '....o...', '........', '........')),
    array('code'=> 0x050, 'patterns' => array( '........', '....o...', '...ooo..', '..o.o.o.', '....o...', '....o...', '....o...', '........')),
    array('code'=> 0x051, 'patterns' => array( '....ooo.', '...oo...', '..oo....', '.oo.....', '..oo....', '...oo...', '....ooo.', '........')),
    array('code'=> 0x052, 'patterns' => array( '..oooo..', '..o.....', '..o.....', '..o.....', '..o.....', '..o.....', '..oooo..', '........')),
    array('code'=> 0x053, 'patterns' => array( '..oo.oo.', '.ooooooo', '.ooooooo', '.ooooooo', '..ooooo.', '...ooo..', '....o...', '........')),
    array('code'=> 0x054, 'patterns' => array( '..oooo..', '.....o..', '.....o..', '.....o..', '.....o..', '.....o..', '..oooo..', '........')),
    array('code'=> 0x055, 'patterns' => array( '...ooo..', '..o...o.', '.o..o.o.', '.o.o.oo.', '.o..oo..', '..o.....', '...oooo.', '........')),
    array('code'=> 0x056, 'patterns' => array( 'oooooooo', 'ooooooo.', 'oooooo..', 'ooooo...', 'oooo....', 'ooo.....', 'oo......', 'o.......')),
    array('code'=> 0x057, 'patterns' => array( '.ooo....', '...oo...', '....oo..', '.....oo.', '....oo..', '...oo...', '.ooo....', '........')),
    array('code'=> 0x058, 'patterns' => array( 'o.o.....', '.o.o....', 'o.o.....', '.o.o....', 'o.o.....', '.o.o....', 'o.o.....', '.o.o....')),
    array('code'=> 0x059, 'patterns' => array( '........', '.o......', '..o.....', '...o....', '....o...', '.....o..', '......o.', '........')),
    array('code'=> 0x05a, 'patterns' => array( 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o')),
    array('code'=> 0x05b, 'patterns' => array( 'oooo....', 'oooo....', 'oooo....', 'oooo....', '....oooo', '....oooo', '....oooo', '....oooo')),
    array('code'=> 0x05c, 'patterns' => array( '........', '........', '........', '........', '....oooo', '....o...', '....o...', '....o...')),
    array('code'=> 0x05d, 'patterns' => array( '........', '........', '........', '........', 'ooooo...', '....o...', '....o...', '....o...')),
    array('code'=> 0x05e, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', 'ooooo...', '....o...', '....o...', '....o...')),
    array('code'=> 0x05f, 'patterns' => array( '........', '........', '........', '........', 'oooooooo', '....o...', '....o...', '....o...')),
    array('code'=> 0x060, 'patterns' => array( '........', '........', '.......o', '..ooooo.', '.o.o.o..', '...o.o..', '...o.o..', '........')),
    array('code'=> 0x061, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', '........', '........', '....o...', '........')),
    array('code'=> 0x062, 'patterns' => array( '..o..o..', '..o..o..', '..o..o..', '........', '........', '........', '........', '........')),
    array('code'=> 0x063, 'patterns' => array( '..o..o..', '..o..o..', '.oooooo.', '..o..o..', '.oooooo.', '..o..o..', '..o..o..', '........')),
    array('code'=> 0x064, 'patterns' => array( '....o...', '...oooo.', '..o.o...', '...ooo..', '....o.o.', '..oooo..', '....o...', '........')),
    array('code'=> 0x065, 'patterns' => array( '........', '.oo...o.', '.oo..o..', '....o...', '...o....', '..o..oo.', '.o...oo.', '........')),
    array('code'=> 0x066, 'patterns' => array( '..oo....', '.o..o...', '.o..o...', '..oo....', '.o..o.o.', '.o...o..', '..ooo.o.', '........')),
    array('code'=> 0x067, 'patterns' => array( '.....o..', '....o...', '...o....', '........', '........', '........', '........', '........')),
    array('code'=> 0x068, 'patterns' => array( '.....o..', '....o...', '...o....', '...o....', '...o....', '....o...', '.....o..', '........')),
    array('code'=> 0x069, 'patterns' => array( '..o.....', '...o....', '....o...', '....o...', '....o...', '...o....', '..o.....', '........')),
    array('code'=> 0x06a, 'patterns' => array( '........', '....o...', '....o...', '..ooooo.', '....o...', '....o...', '........', '........')),
    array('code'=> 0x06b, 'patterns' => array( '....o...', '..o.o.o.', '...ooo..', '..ooooo.', '...ooo..', '..o.o.o.', '....o...', '........')),
    array('code'=> 0x06c, 'patterns' => array( '....oooo', '....oooo', '....oooo', '....oooo', 'oooo....', 'oooo....', 'oooo....', 'oooo....')),
    array('code'=> 0x06d, 'patterns' => array( 'o......o', '.o....o.', '..o..o..', '...oo...', '...oo...', '..o..o..', '.o....o.', 'o......o')),
    array('code'=> 0x06e, 'patterns' => array( '...o....', '...o....', '..o.....', 'oo......', '........', '........', '........', '........')),
    array('code'=> 0x06f, 'patterns' => array( '....o...', '....o...', '.....o..', '......oo', '........', '........', '........', '........')),
    array('code'=> 0x070, 'patterns' => array( 'oooooooo', '........', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x071, 'patterns' => array( 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......')),
    array('code'=> 0x072, 'patterns' => array( 'oooooooo', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......')),
    array('code'=> 0x073, 'patterns' => array( 'oooooooo', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o')),
    array('code'=> 0x074, 'patterns' => array( '........', '........', 'oooooooo', '........', '........', '........', '........', '........')),
    array('code'=> 0x075, 'patterns' => array( '..o.....', '..o.....', '..o.....', '..o.....', '..o.....', '..o.....', '..o.....', '..o.....')),
    array('code'=> 0x076, 'patterns' => array( '.......o', '......o.', '.....o..', '....o...', '...o....', '..o.....', '.o......', 'o.......')),
    array('code'=> 0x077, 'patterns' => array( 'o.......', '.o......', '..o.....', '...o....', '....o...', '.....o..', '......o.', '.......o')),
    array('code'=> 0x078, 'patterns' => array( '........', '........', '........', '........', 'oooooooo', '........', '........', '........')),
    array('code'=> 0x079, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', '....o...', '....o...', '....o...', '....o...')),
    array('code'=> 0x07a, 'patterns' => array( 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', '........', '........', '........', '........')),
    array('code'=> 0x07b, 'patterns' => array( 'oooo....', 'oooo....', 'oooo....', 'oooo....', 'oooo....', 'oooo....', 'oooo....', 'oooo....')),
    array('code'=> 0x07c, 'patterns' => array( '........', '........', '........', '........', '........', '........', 'oooooooo', '........')),
    array('code'=> 0x07d, 'patterns' => array( '......o.', '......o.', '......o.', '......o.', '......o.', '......o.', '......o.', '......o.')),
    array('code'=> 0x07e, 'patterns' => array( '........', '........', '........', '........', '........', 'oooooooo', 'oooooooo', 'oooooooo')),
    array('code'=> 0x07f, 'patterns' => array( '.....ooo', '.....ooo', '.....ooo', '.....ooo', '.....ooo', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x080, 'patterns' => array( '........', '....o...', '....o...', '....o...', '..o.o.o.', '...ooo..', '....o...', '........')),
    array('code'=> 0x081, 'patterns' => array( '.....o..', '..ooo...', '....o...', '..ooooo.', '....o...', '....o...', '...o....', '........')),
    array('code'=> 0x082, 'patterns' => array( '........', '..ooooo.', '......o.', '......o.', '......o.', '......o.', '..ooooo.', '........')),
    array('code'=> 0x083, 'patterns' => array( '........', '..o...o.', '..o...o.', '...o..o.', '......o.', '.....o..', '...oo...', '........')),
    array('code'=> 0x084, 'patterns' => array( '........', '..oo....', '......o.', '..oo..o.', '......o.', '.....o..', '..ooo...', '........')),
    array('code'=> 0x085, 'patterns' => array( '......o.', '.....o..', '....o...', '...oo...', '..o.o...', '....o...', '....o...', '........')),
    array('code'=> 0x086, 'patterns' => array( '........', '....o...', '.....o..', '..o...o.', '..o...o.', '..o...o.', '..o...o.', '........')),
    array('code'=> 0x087, 'patterns' => array( '....o...', '..ooooo.', '....o...', '..ooooo.', '....o...', '....o...', '....o...', '........')),
    array('code'=> 0x088, 'patterns' => array( '........', '...oooo.', '...o..o.', '..o...o.', '......o.', '.....o..', '...oo...', '........')),
    array('code'=> 0x089, 'patterns' => array( '........', '...ooo..', '........', '........', '........', '........', '..ooooo.', '........')),
    array('code'=> 0x08a, 'patterns' => array( '........', '..ooooo.', '......o.', '......o.', '...o.o..', '....o...', '.....o..', '........')),
    array('code'=> 0x08b, 'patterns' => array( '.....o..', '.....o..', '.....o..', '.....o..', '.....o..', '....o...', '...o....', '........')),
    array('code'=> 0x08c, 'patterns' => array( '..o..o..', '..o..o..', '..o..o..', '..o..o..', '.....o..', '....o...', '...o....', '........')),
    array('code'=> 0x08d, 'patterns' => array( '........', '..ooooo.', '...o....', '..ooooo.', '...o....', '...o....', '....ooo.', '........')),
    array('code'=> 0x08e, 'patterns' => array( '........', '...ooo..', '........', '...ooo..', '........', '..oooo..', '......o.', '........')),
    array('code'=> 0x08f, 'patterns' => array( '...ooo..', '........', '..ooooo.', '......o.', '......o.', '.....o..', '....o...', '........')),
    array('code'=> 0x090, 'patterns' => array( '...o....', '..ooooo.', '...o..o.', '...o.o..', '...o....', '...o....', '....ooo.', '........')),
    array('code'=> 0x091, 'patterns' => array( '........', '...oooo.', '...o..o.', '..o.o.o.', '.....oo.', '.....o..', '...oo...', '........')),
    array('code'=> 0x092, 'patterns' => array( '........', '..ooooo.', '......o.', '.....o..', '....o...', '...o.o..', '..o...o.', '........')),
    array('code'=> 0x093, 'patterns' => array( '...o....', '...o....', '...o....', '...oo...', '...o.o..', '...o....', '...o....', '........')),
    array('code'=> 0x094, 'patterns' => array( '...o....', '..ooooo.', '...o..o.', '...o..o.', '...o..o.', '...o..o.', '..o..o..', '........')),
    array('code'=> 0x095, 'patterns' => array( '....o...', '....o...', '..ooooo.', '....o...', '....o...', '...o....', '..o.....', '........')),
    array('code'=> 0x096, 'patterns' => array( '..o.....', '..o.....', '..ooooo.', '..o.....', '..o.....', '..o.....', '...oooo.', '........')),
    array('code'=> 0x097, 'patterns' => array( '...ooo..', '........', '..ooooo.', '....o...', '....o...', '....o...', '...o....', '........')),
    array('code'=> 0x098, 'patterns' => array( '...o.o..', '..ooooo.', '...o.o..', '...o.o..', '.....o..', '....o...', '...o....', '........')),
    array('code'=> 0x099, 'patterns' => array( '........', '..oo....', '........', '......o.', '......o.', '.....o..', '..ooo...', '........')),
    array('code'=> 0x09a, 'patterns' => array( '........', '..o.o.o.', '..o.o.o.', '..o.o.o.', '......o.', '.....o..', '....o...', '........')),
    array('code'=> 0x09b, 'patterns' => array( '........', '..ooooo.', '..o...o.', '..o...o.', '..o...o.', '..o...o.', '..ooooo.', '........')),
    array('code'=> 0x09c, 'patterns' => array( '...o....', '...oooo.', '..o..o..', '.....o..', '.....o..', '.....o..', '....o...', '........')),
    array('code'=> 0x09d, 'patterns' => array( '...oooo.', '...o....', '...o....', '...o....', '........', '........', '........', '........')),
    array('code'=> 0x09e, 'patterns' => array( '........', '........', '..ooooo.', '......o.', '....oo..', '....o...', '...o....', '........')),
    array('code'=> 0x09f, 'patterns' => array( '........', '........', '...o....', '..ooooo.', '...o..o.', '...o.o..', '...o....', '........')),
    array('code'=> 0x0a0, 'patterns' => array( '........', '..ooooo.', '..o...o.', '..o...o.', '......o.', '.....o..', '....o...', '........')),
    array('code'=> 0x0a1, 'patterns' => array( '........', '..ooooo.', '......o.', '...o.o..', '....o...', '...o.o..', '..o.....', '........')),
    array('code'=> 0x0a2, 'patterns' => array( '........', '..ooooo.', '......o.', '......o.', '......o.', '.....o..', '...oo...', '........')),
    array('code'=> 0x0a3, 'patterns' => array( '..ooooo.', '......o.', '....o.o.', '....oo..', '....o...', '....o...', '...o....', '........')),
    array('code'=> 0x0a4, 'patterns' => array( '....o...', '..ooooo.', '..o...o.', '..o...o.', '......o.', '.....o..', '....o...', '........')),
    array('code'=> 0x0a5, 'patterns' => array( '........', '..ooooo.', '....o...', '....o...', '....o...', '....o...', '..ooooo.', '........')),
    array('code'=> 0x0a6, 'patterns' => array( '.....o..', '..ooooo.', '.....o..', '....oo..', '...o.o..', '..o..o..', '.....o..', '........')),
    array('code'=> 0x0a7, 'patterns' => array( '...o....', '...o....', '..ooooo.', '...o..o.', '...o.o..', '...o....', '...o....', '........')),
    array('code'=> 0x0a8, 'patterns' => array( '........', '...ooo..', '.....o..', '.....o..', '.....o..', '.....o..', '..ooooo.', '........')),
    array('code'=> 0x0a9, 'patterns' => array( '........', '..ooooo.', '......o.', '..ooooo.', '......o.', '......o.', '..ooooo.', '........')),
    array('code'=> 0x0aa, 'patterns' => array( '....o...', '..ooooo.', '....o...', '....o...', '..o.o.o.', '..o.o.o.', '....o...', '........')),
    array('code'=> 0x0ab, 'patterns' => array( '........', '...o....', '..o.o...', '.....o..', '......o.', '......o.', '........', '........')),
    array('code'=> 0x0ac, 'patterns' => array( '........', '..o.....', '..o.....', '..o...o.', '..o..o..', '..o.o...', '..oo....', '........')),
    array('code'=> 0x0ad, 'patterns' => array( '........', '......o.', '......o.', '...o.o..', '....o...', '...o.o..', '..o.....', '........')),
    array('code'=> 0x0ae, 'patterns' => array( '........', '....o...', '..o.o...', '..o.o...', '..o.o.o.', '..o.o.o.', '..o.oo..', '........')),
    array('code'=> 0x0af, 'patterns' => array( '....o...', '..ooooo.', '.....o..', '....o...', '...ooo..', '..o.o.o.', '....o...', '........')),
    array('code'=> 0x0b0, 'patterns' => array( '........', '....o...', '...o....', '..o.....', '..o...o.', '..ooooo.', '......o.', '........')),
    array('code'=> 0x0b1, 'patterns' => array( '........', '........', '........', '....o...', '....o...', '....o...', '.oooo...', '........')),
    array('code'=> 0x0b2, 'patterns' => array( '........', '........', '.....o..', '....o...', '...oo...', '..o.o...', '....o...', '........')),
    array('code'=> 0x0b3, 'patterns' => array( '........', '........', '........', '...ooo..', '.....o..', '.....o..', '..ooooo.', '........')),
    array('code'=> 0x0b4, 'patterns' => array( '........', '..ooooo.', '......o.', '..ooooo.', '......o.', '.....o..', '....o...', '........')),
    array('code'=> 0x0b5, 'patterns' => array( '........', '........', '........', '........', '.o......', '..o.....', '...o....', '........')),
    array('code'=> 0x0b6, 'patterns' => array( '........', '........', '....o...', '..ooooo.', '..o...o.', '......o.', '....oo..', '........')),
    array('code'=> 0x0b7, 'patterns' => array( '........', '........', '..oooo..', '.....o..', '..oooo..', '.....o..', '..oooo..', '........')),
    array('code'=> 0x0b8, 'patterns' => array( '.ooo....', '.o.o....', '.ooo....', '........', '........', '........', '........', '........')),
    array('code'=> 0x0b9, 'patterns' => array( '........', '........', '........', '........', '........', '........', '..o.....', '........')),
    array('code'=> 0x0ba, 'patterns' => array( '........', '........', '........', '..ooooo.', '....o...', '....o...', '..ooooo.', '........')),
    array('code'=> 0x0bb, 'patterns' => array( '........', '........', '........', '..o.o.o.', '..o.o.o.', '......o.', '....oo..', '........')),
    array('code'=> 0x0bc, 'patterns' => array( '...o....', '.o..o...', '..o.....', '........', '........', '........', '........', '........')),
    array('code'=> 0x0bd, 'patterns' => array( '........', '........', '........', '........', '.ooo....', '.o.o....', '.ooo....', '........')),
    array('code'=> 0x0be, 'patterns' => array( '........', '........', '.....o..', '..ooooo.', '....oo..', '...o.o..', '..o..o..', '........')),
    array('code'=> 0x0bf, 'patterns' => array( '........', '........', '........', '...ooo..', '........', '........', '........', '........')),
    array('code'=> 0x0c0, 'patterns' => array( '...ooo..', '...ooo..', '..ooooo.', '...ooo..', '....o...', '........', '..ooooo.', '........')),
    array('code'=> 0x0c1, 'patterns' => array( 'oooooooo', 'oooo.ooo', 'oooo.ooo', 'oooo.ooo', 'oo.o.o.o', 'ooo...oo', 'oooo.ooo', 'oooooooo')),
    array('code'=> 0x0c2, 'patterns' => array( 'oooooooo', 'oooo.ooo', 'ooo...oo', 'oo.o.o.o', 'oooo.ooo', 'oooo.ooo', 'oooo.ooo', 'oooooooo')),
    array('code'=> 0x0c3, 'patterns' => array( 'oooooooo', 'oooooooo', 'oooo.ooo', 'ooooo.oo', 'o......o', 'ooooo.oo', 'oooo.ooo', 'oooooooo')),
    array('code'=> 0x0c4, 'patterns' => array( 'oooooooo', 'oooooooo', 'ooo.oooo', 'oo.ooooo', 'o......o', 'oo.ooooo', 'ooo.oooo', 'oooooooo')),
    array('code'=> 0x0c5, 'patterns' => array( 'o.ooo.oo', 'o.ooo.oo', 'o.ooo.oo', 'o.....oo', 'o.ooo.oo', 'o.ooo.oo', 'o.ooo.oo', 'oooooooo')),
    array('code'=> 0x0c6, 'patterns' => array( 'ooo...oo', 'oo.ooo.o', 'o.oooooo', 'o.oooooo', 'o.oooooo', 'oo.ooo.o', 'ooo...oo', 'oooooooo')),
    array('code'=> 0x0c7, 'patterns' => array( '...oo...', '..o..o..', '.oooooo.', 'oooooooo', '.o.oo.o.', '..o..o..', '........', '........')),
    array('code'=> 0x0c8, 'patterns' => array( 'ooo.....', '.o...ooo', '.o....o.', '.oooooo.', '.o....o.', '.o...ooo', 'ooo.....', '........')),
    array('code'=> 0x0c9, 'patterns' => array( '..o...o.', '..ooooo.', '..o.o.o.', '....o...', '....o...', '.o..o..o', '.ooooooo', '.o.....o')),
    array('code'=> 0x0ca, 'patterns' => array( '...ooo..', '...ooo..', '....o...', '..ooooo.', '....o...', '....o...', '...o.o..', '..o...o.')),
    array('code'=> 0x0cb, 'patterns' => array( '........', '...o...o', 'oo.o..o.', 'oooooo..', 'oo.o..o.', '...o...o', '........', '........')),
    array('code'=> 0x0cc, 'patterns' => array( '........', 'o...o...', '.o..o.oo', '..oooooo', '.o..o.oo', 'o...o...', '........', '........')),
    array('code'=> 0x0cd, 'patterns' => array( '..o...o.', '...o.o..', '....o...', '....o...', '..ooooo.', '....o...', '...ooo..', '...ooo..')),
    array('code'=> 0x0ce, 'patterns' => array( '..oooo..', '.oooooo.', 'oooooooo', 'oo.oo.oo', 'oooooooo', 'ooo..ooo', '.oooooo.', '..oooo..')),
    array('code'=> 0x0cf, 'patterns' => array( '..oooo..', '.o....o.', 'o......o', 'o.o..o.o', 'o......o', 'o..oo..o', '.o....o.', '..oooo..')),
    array('code'=> 0x0d0, 'patterns' => array( '..ooooo.', '..o...o.', '..o...o.', '..ooooo.', '..o...o.', '..o...o.', '..ooooo.', '........')),
    array('code'=> 0x0d1, 'patterns' => array( '..ooooo.', '..o...o.', '..ooooo.', '..o...o.', '..ooooo.', '..o...o.', '.o....o.', '........')),
    array('code'=> 0x0d2, 'patterns' => array( '....o...', '..o.o.o.', '..o.o.o.', '....o...', '...o.o..', '..o...o.', '.o.....o', '........')),
    array('code'=> 0x0d3, 'patterns' => array( '....o...', '....o..o', '..ooo.o.', '....oo..', '...ooo..', '..o.o.o.', '.o..o..o', '........')),
    array('code'=> 0x0d4, 'patterns' => array( '....o...', '....o...', '..ooooo.', '....o...', '...ooo..', '..o.o.o.', '.o..o..o', '........')),
    array('code'=> 0x0d5, 'patterns' => array( '....o...', '...o.o..', '..ooooo.', '.o..o..o', '..ooooo.', '...ooo..', '.ooooooo', '........')),
    array('code'=> 0x0d6, 'patterns' => array( '........', '....o...', '....o...', '..ooooo.', '....o...', '....o...', '.ooooooo', '........')),
    array('code'=> 0x0d7, 'patterns' => array( '....o...', '.o..o...', '.oooooo.', '.o..o...', '..ooooo.', '....o...', '.ooooooo', '........')),
    array('code'=> 0x0d8, 'patterns' => array( '..o.....', '..ooooo.', '.o..o...', '..oooo..', '..o.o...', '.oooooo.', '....o...', '........')),
    array('code'=> 0x0d9, 'patterns' => array( '.....o..', '.oooooo.', '.o.o.o..', '.ooooooo', '.o.o..o.', '.ooooooo', '....o.o.', '........')),
    array('code'=> 0x0da, 'patterns' => array( '....o...', '...o.o..', '..o...o.', '.ooooooo', '...o..o.', '...o..o.', '..o..o..', '........')),
    array('code'=> 0x0db, 'patterns' => array( '..ooo...', '...o..o.', '.ooooooo', '...o.ooo', '..ooo.oo', '.o.o..o.', '...o.o..', '........')),
    array('code'=> 0x0dc, 'patterns' => array( '.ooooooo', '.o..o..o', '.o..o..o', '.ooooooo', '.o.....o', '.o.....o', '.o.....o', '........')),
    array('code'=> 0x0dd, 'patterns' => array( '..o...o.', '...o.o..', '..ooooo.', '....o...', '..ooooo.', '....o...', '....o...', '........')),
    array('code'=> 0x0de, 'patterns' => array( '....oo..', '...o..o.', '...o....', '..ooo...', '...o....', '...o....', '..ooooo.', '........')),
    array('code'=> 0x0df, 'patterns' => array( '........', 'oo......', 'oo..o...', '.o.o.o..', '.o.o.o..', '.o.o.o.o', '..o...o.', '........')),
    array('code'=> 0x0e0, 'patterns' => array( '........', '........', '........', '........', '........', '......o.', 'oooooooo', '......o.')),
    array('code'=> 0x0e1, 'patterns' => array( '......o.', '......o.', '......o.', '......o.', '......o.', '......o.', '.....ooo', '......o.')),
    array('code'=> 0x0e2, 'patterns' => array( '......o.', '......o.', '......o.', '......o.', '......o.', '......o.', 'oooooooo', '......o.')),
    array('code'=> 0x0e3, 'patterns' => array( '........', '........', '..o.....', '.o.o....', 'o...o...', '.....o.o', '......o.', '........')),
    array('code'=> 0x0e4, 'patterns' => array( '........', '....ooo.', '...o...o', '..o...o.', 'oo...o..', '.....o..', '......o.', '.......o')),
    array('code'=> 0x0e5, 'patterns' => array( '........', 'oooooooo', '........', 'o......o', '.o....o.', '.o....o.', 'o......o', '........')),
    array('code'=> 0x0e6, 'patterns' => array( '........', '.ooo....', 'o...o...', '.o...o..', '..o...oo', '..o.....', '.o......', 'o.......')),
    array('code'=> 0x0e7, 'patterns' => array( '........', 'oo...o..', 'o.o..o..', 'o..o.o..', 'o...oooo', 'o..o.o..', 'o.o..o..', 'oo...o..')),
    array('code'=> 0x0e8, 'patterns' => array( '........', '..o...oo', '..o..o.o', '..o.o..o', 'oooo...o', '..o.o..o', '..o..o.o', '..o...oo')),
    array('code'=> 0x0e9, 'patterns' => array( 'o...o...', 'o..o....', 'o.o.....', 'oo......', 'oo......', 'o.o.o...', 'o..oo...', 'o.ooo...')),
    array('code'=> 0x0ea, 'patterns' => array( 'o.o.o...', 'o.oo....', 'o.ooo...', 'oo......', 'oo......', 'o.o.....', 'o..o....', 'o...o...')),
    array('code'=> 0x0eb, 'patterns' => array( 'o.......', '.o......', '..o.....', '...o....', '...ooooo', '..o.....', '.o......', 'o.......')),
    array('code'=> 0x0ec, 'patterns' => array( '........', '........', '..o..o..', '..o..o..', 'ooo..ooo', '..o..o..', '..o..o..', '........')),
    array('code'=> 0x0ed, 'patterns' => array( '....o...', '....o...', '..ooooo.', '........', '........', '..ooooo.', '....o...', '....o...')),
    array('code'=> 0x0ee, 'patterns' => array( '....o...', '...o....', '..o.....', '...o....', '....o...', '.....o..', '......o.', '.....o..')),
    array('code'=> 0x0ef, 'patterns' => array( '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.')),
    array('code'=> 0x0f0, 'patterns' => array( '........', '........', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x0f1, 'patterns' => array( '........', '.ooo....', '.ooo....', '.ooo....', '........', '........', '........', '........')),
    array('code'=> 0x0f2, 'patterns' => array( '........', '.....ooo', '.....ooo', '.....ooo', '........', '........', '........', '........')),
    array('code'=> 0x0f3, 'patterns' => array( '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo', '........', '........', '........', '........')),
    array('code'=> 0x0f4, 'patterns' => array( '........', '........', '........', '........', '........', '.ooo....', '.ooo....', '.ooo....')),
    array('code'=> 0x0f5, 'patterns' => array( '........', '.ooo....', '.ooo....', '.ooo....', '........', '.ooo....', '.ooo....', '.ooo....')),
    array('code'=> 0x0f6, 'patterns' => array( '........', '.....ooo', '.....ooo', '.....ooo', '........', '.ooo....', '.ooo....', '.ooo....')),
    array('code'=> 0x0f7, 'patterns' => array( '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo', '........', '.ooo....', '.ooo....', '.ooo....')),
    array('code'=> 0x0f8, 'patterns' => array( '........', '........', '........', '........', '........', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x0f9, 'patterns' => array( '........', '.ooo....', '.ooo....', '.ooo....', '........', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x0fa, 'patterns' => array( '........', '.....ooo', '.....ooo', '.....ooo', '........', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x0fb, 'patterns' => array( '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo', '........', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x0fc, 'patterns' => array( '........', '........', '........', '........', '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo')),
    array('code'=> 0x0fd, 'patterns' => array( '........', '.ooo....', '.ooo....', '.ooo....', '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo')),
    array('code'=> 0x0fe, 'patterns' => array( '........', '.....ooo', '.....ooo', '.....ooo', '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo')),
    array('code'=> 0x0ff, 'patterns' => array( '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo', '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo')),
    array('code'=> 0x100, 'patterns' => array( '........', '........', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x101, 'patterns' => array( '........', '........', '..ooo...', '.....o..', '..oooo..', '.o...o..', '..ooo.o.', '........')),
    array('code'=> 0x102, 'patterns' => array( '.o......', '.o......', '.o.ooo..', '.oo...o.', '.o....o.', '.oo...o.', '.o.ooo..', '........')),
    array('code'=> 0x103, 'patterns' => array( '........', '........', '..oooo..', '.o....o.', '.o......', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x104, 'patterns' => array( '......o.', '......o.', '..ooo.o.', '.o...oo.', '.o....o.', '.o...oo.', '..ooo.o.', '........')),
    array('code'=> 0x105, 'patterns' => array( '........', '........', '..oooo..', '.o....o.', '.oooooo.', '.o......', '..oooo..', '........')),
    array('code'=> 0x106, 'patterns' => array( '....oo..', '...o..o.', '...o....', '.ooooo..', '...o....', '...o....', '...o....', '........')),
    array('code'=> 0x107, 'patterns' => array( '........', '........', '..ooo.o.', '.o...oo.', '.o...oo.', '..ooo.o.', '......o.', '..oooo..')),
    array('code'=> 0x108, 'patterns' => array( '.o......', '.o......', '.o.ooo..', '.oo...o.', '.o....o.', '.o....o.', '.o....o.', '........')),
    array('code'=> 0x109, 'patterns' => array( '....o...', '........', '...oo...', '....o...', '....o...', '....o...', '...ooo..', '........')),
    array('code'=> 0x10a, 'patterns' => array( '.....o..', '........', '....oo..', '.....o..', '.....o..', '.....o..', '.o...o..', '..ooo...')),
    array('code'=> 0x10b, 'patterns' => array( '.o......', '.o......', '.o...o..', '.o..o...', '.o.o....', '.oo.o...', '.o...o..', '........')),
    array('code'=> 0x10c, 'patterns' => array( '...oo...', '....o...', '....o...', '....o...', '....o...', '....o...', '...ooo..', '........')),
    array('code'=> 0x10d, 'patterns' => array( '........', '........', '.ooo.oo.', '.o..o..o', '.o..o..o', '.o..o..o', '.o..o..o', '........')),
    array('code'=> 0x10e, 'patterns' => array( '........', '........', '.o.ooo..', '.oo...o.', '.o....o.', '.o....o.', '.o....o.', '........')),
    array('code'=> 0x10f, 'patterns' => array( '........', '........', '..oooo..', '.o....o.', '.o....o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x110, 'patterns' => array( '........', '........', '.o.ooo..', '.oo...o.', '.oo...o.', '.o.ooo..', '.o......', '.o......')),
    array('code'=> 0x111, 'patterns' => array( '........', '........', '..ooo.o.', '.o...oo.', '.o...oo.', '..ooo.o.', '......o.', '......o.')),
    array('code'=> 0x112, 'patterns' => array( '........', '........', '.o.ooo..', '.oo...o.', '.o......', '.o......', '.o......', '........')),
    array('code'=> 0x113, 'patterns' => array( '........', '........', '..ooooo.', '.o......', '..oooo..', '......o.', '.ooooo..', '........')),
    array('code'=> 0x114, 'patterns' => array( '...o....', '...o....', '.ooooo..', '...o....', '...o....', '...o..o.', '....oo..', '........')),
    array('code'=> 0x115, 'patterns' => array( '........', '........', '.o....o.', '.o....o.', '.o....o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x116, 'patterns' => array( '........', '........', '.o....o.', '.o....o.', '.o....o.', '..o..o..', '...oo...', '........')),
    array('code'=> 0x117, 'patterns' => array( '........', '........', '.o.....o', '.o..o..o', '.o..o..o', '.o..o..o', '..oo.oo.', '........')),
    array('code'=> 0x118, 'patterns' => array( '........', '........', '.o...o..', '..o.o...', '...o....', '..o.o...', '.o...o..', '........')),
    array('code'=> 0x119, 'patterns' => array( '........', '........', '.o....o.', '.o....o.', '.o...oo.', '..ooo.o.', '......o.', '..oooo..')),
    array('code'=> 0x11a, 'patterns' => array( '........', '........', '.oooooo.', '.....o..', '...oo...', '..o.....', '.oooooo.', '........')),
    array('code'=> 0x11b, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', 'oooooooo', '....o...', '....o...', '....o...')),
    array('code'=> 0x11c, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', '....oooo', '........', '........', '........')),
    array('code'=> 0x11d, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', 'ooooo...', '........', '........', '........')),
    array('code'=> 0x11e, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', '....oooo', '....o...', '....o...', '....o...')),
    array('code'=> 0x11f, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', 'oooooooo', '........', '........', '........')),
    array('code'=> 0x120, 'patterns' => array( '..oooo..', '.o....o.', '.o...oo.', '.o.oo.o.', '.oo...o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x121, 'patterns' => array( '....o...', '...oo...', '..o.o...', '....o...', '....o...', '....o...', '..ooooo.', '........')),
    array('code'=> 0x122, 'patterns' => array( '..oooo..', '.o....o.', '......o.', '....oo..', '..oo....', '.o......', '.oooooo.', '........')),
    array('code'=> 0x123, 'patterns' => array( '..oooo..', '.o....o.', '......o.', '..oooo..', '......o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x124, 'patterns' => array( '.....o..', '....oo..', '...o.o..', '..o..o..', '.oooooo.', '.....o..', '.....o..', '........')),
    array('code'=> 0x125, 'patterns' => array( '.oooooo.', '.o......', '.oooo...', '.....o..', '......o.', '.o...o..', '..ooo...', '........')),
    array('code'=> 0x126, 'patterns' => array( '...ooo..', '..o.....', '.o......', '.ooooo..', '.o....o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x127, 'patterns' => array( '.oooooo.', '.o....o.', '.....o..', '....o...', '...o....', '...o....', '...o....', '........')),
    array('code'=> 0x128, 'patterns' => array( '..oooo..', '.o....o.', '.o....o.', '..oooo..', '.o....o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x129, 'patterns' => array( '..oooo..', '.o....o.', '.o....o.', '..ooooo.', '......o.', '.....o..', '..ooo...', '........')),
    array('code'=> 0x12a, 'patterns' => array( '........', '........', '........', '.oooooo.', '........', '........', '........', '........')),
    array('code'=> 0x12b, 'patterns' => array( '........', '........', '.oooooo.', '........', '.oooooo.', '........', '........', '........')),
    array('code'=> 0x12c, 'patterns' => array( '........', '........', '....o...', '........', '........', '....o...', '....o...', '...o....')),
    array('code'=> 0x12d, 'patterns' => array( '........', '......o.', '.....o..', '....o...', '...o....', '..o.....', '.o......', '........')),
    array('code'=> 0x12e, 'patterns' => array( '........', '........', '........', '........', '........', '...oo...', '...oo...', '........')),
    array('code'=> 0x12f, 'patterns' => array( '........', '........', '........', '........', '........', '....o...', '....o...', '...o....')),
    array('code'=> 0x130, 'patterns' => array( '........', 'oooooooo', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x131, 'patterns' => array( '.o......', '.o......', '.o......', '.o......', '.o......', '.o......', '.o......', '.o......')),
    array('code'=> 0x132, 'patterns' => array( 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'oooooooo')),
    array('code'=> 0x133, 'patterns' => array( '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', 'oooooooo')),
    array('code'=> 0x134, 'patterns' => array( '........', '........', '........', 'oooooooo', '........', '........', '........', '........')),
    array('code'=> 0x135, 'patterns' => array( '...o....', '...o....', '...o....', '...o....', '...o....', '...o....', '...o....', '...o....')),
    array('code'=> 0x136, 'patterns' => array( 'oooooooo', 'oooooooo', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x137, 'patterns' => array( 'oo......', 'oo......', 'oo......', 'oo......', 'oo......', 'oo......', 'oo......', 'oo......')),
    array('code'=> 0x138, 'patterns' => array( '........', '........', '........', '........', '........', 'oooooooo', '........', '........')),
    array('code'=> 0x139, 'patterns' => array( '.....o..', '.....o..', '.....o..', '.....o..', '.....o..', '.....o..', '.....o..', '.....o..')),
    array('code'=> 0x13a, 'patterns' => array( '........', '........', '........', '........', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo')),
    array('code'=> 0x13b, 'patterns' => array( '....oooo', '....oooo', '....oooo', '....oooo', '....oooo', '....oooo', '....oooo', '....oooo')),
    array('code'=> 0x13c, 'patterns' => array( '........', '........', '........', '........', '........', '........', '........', 'oooooooo')),
    array('code'=> 0x13d, 'patterns' => array( '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o')),
    array('code'=> 0x13e, 'patterns' => array( '........', '........', '........', '........', '........', '........', 'oooooooo', 'oooooooo')),
    array('code'=> 0x13f, 'patterns' => array( '......oo', '......oo', '......oo', '......oo', '......oo', '......oo', '......oo', '......oo')),
    array('code'=> 0x140, 'patterns' => array( '........', '........', '....o...', '.....o..', 'ooooooo.', '.....o..', '....o...', '........')),
    array('code'=> 0x141, 'patterns' => array( '....o...', '...ooo..', '..ooooo.', '.ooooooo', '.ooooooo', '...ooo..', '..ooooo.', '........')),
    array('code'=> 0x142, 'patterns' => array( 'oooooooo', '.ooooooo', '..oooooo', '...ooooo', '....oooo', '.....ooo', '......oo', '.......o')),
    array('code'=> 0x143, 'patterns' => array( 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo')),
    array('code'=> 0x144, 'patterns' => array( '....o...', '...ooo..', '..ooooo.', '.ooooooo', '..ooooo.', '...ooo..', '....o...', '........')),
    array('code'=> 0x145, 'patterns' => array( '........', '........', '...o....', '..o.....', '.ooooooo', '..o.....', '...o....', '........')),
    array('code'=> 0x146, 'patterns' => array( '....o...', '...ooo..', '..o.o.o.', '.ooooooo', '..o.o.o.', '....o...', '....o...', '........')),
    array('code'=> 0x147, 'patterns' => array( '........', '..oooo..', '.oooooo.', '.oooooo.', '.oooooo.', '.oooooo.', '..oooo..', '........')),
    array('code'=> 0x148, 'patterns' => array( '........', '..oooo..', '.o....o.', '.o....o.', '.o....o.', '.o....o.', '..oooo..', '........')),
    array('code'=> 0x149, 'patterns' => array( '..oooo..', '.o....o.', '......o.', '....oo..', '...o....', '........', '...o....', '........')),
    array('code'=> 0x14a, 'patterns' => array( 'oooooooo', 'oo....oo', 'o......o', 'o......o', 'o......o', 'o......o', 'oo....oo', 'oooooooo')),
    array('code'=> 0x14b, 'patterns' => array( '........', '........', '........', '........', '......oo', '.....o..', '....o...', '....o...')),
    array('code'=> 0x14c, 'patterns' => array( '........', '........', '........', '........', 'oo......', '..o.....', '...o....', '...o....')),
    array('code'=> 0x14d, 'patterns' => array( 'o.......', 'oo......', 'ooo.....', 'oooo....', 'ooooo...', 'oooooo..', 'ooooooo.', 'oooooooo')),
    array('code'=> 0x14e, 'patterns' => array( '.......o', '......oo', '.....ooo', '....oooo', '...ooooo', '..oooooo', '.ooooooo', 'oooooooo')),
    array('code'=> 0x14f, 'patterns' => array( '........', '........', '....o...', '........', '........', '....o...', '........', '........')),
    array('code'=> 0x150, 'patterns' => array( '........', '....o...', '...ooo..', '..o.o.o.', '....o...', '....o...', '....o...', '........')),
    array('code'=> 0x151, 'patterns' => array( '....ooo.', '...oo...', '..oo....', '.oo.....', '..oo....', '...oo...', '....ooo.', '........')),
    array('code'=> 0x152, 'patterns' => array( '..oooo..', '..o.....', '..o.....', '..o.....', '..o.....', '..o.....', '..oooo..', '........')),
    array('code'=> 0x153, 'patterns' => array( '..oo.oo.', '.ooooooo', '.ooooooo', '.ooooooo', '..ooooo.', '...ooo..', '....o...', '........')),
    array('code'=> 0x154, 'patterns' => array( '..oooo..', '.....o..', '.....o..', '.....o..', '.....o..', '.....o..', '..oooo..', '........')),
    array('code'=> 0x155, 'patterns' => array( '...ooo..', '..o...o.', '.o..o.o.', '.o.o.oo.', '.o..oo..', '..o.....', '...oooo.', '........')),
    array('code'=> 0x156, 'patterns' => array( 'oooooooo', 'ooooooo.', 'oooooo..', 'ooooo...', 'oooo....', 'ooo.....', 'oo......', 'o.......')),
    array('code'=> 0x157, 'patterns' => array( '.ooo....', '...oo...', '....oo..', '.....oo.', '....oo..', '...oo...', '.ooo....', '........')),
    array('code'=> 0x158, 'patterns' => array( 'o.o.....', '.o.o....', 'o.o.....', '.o.o....', 'o.o.....', '.o.o....', 'o.o.....', '.o.o....')),
    array('code'=> 0x159, 'patterns' => array( '........', '.o......', '..o.....', '...o....', '....o...', '.....o..', '......o.', '........')),
    array('code'=> 0x15a, 'patterns' => array( 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o')),
    array('code'=> 0x15b, 'patterns' => array( 'oooo....', 'oooo....', 'oooo....', 'oooo....', '....oooo', '....oooo', '....oooo', '....oooo')),
    array('code'=> 0x15c, 'patterns' => array( '........', '........', '........', '........', '....oooo', '....o...', '....o...', '....o...')),
    array('code'=> 0x15d, 'patterns' => array( '........', '........', '........', '........', 'ooooo...', '....o...', '....o...', '....o...')),
    array('code'=> 0x15e, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', 'ooooo...', '....o...', '....o...', '....o...')),
    array('code'=> 0x15f, 'patterns' => array( '........', '........', '........', '........', 'oooooooo', '....o...', '....o...', '....o...')),
    array('code'=> 0x160, 'patterns' => array( '........', '........', '.......o', '..ooooo.', '.o.o.o..', '...o.o..', '...o.o..', '........')),
    array('code'=> 0x161, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', '........', '........', '....o...', '........')),
    array('code'=> 0x162, 'patterns' => array( '..o..o..', '..o..o..', '..o..o..', '........', '........', '........', '........', '........')),
    array('code'=> 0x163, 'patterns' => array( '..o..o..', '..o..o..', '.oooooo.', '..o..o..', '.oooooo.', '..o..o..', '..o..o..', '........')),
    array('code'=> 0x164, 'patterns' => array( '....o...', '...oooo.', '..o.o...', '...ooo..', '....o.o.', '..oooo..', '....o...', '........')),
    array('code'=> 0x165, 'patterns' => array( '........', '.oo...o.', '.oo..o..', '....o...', '...o....', '..o..oo.', '.o...oo.', '........')),
    array('code'=> 0x166, 'patterns' => array( '..oo....', '.o..o...', '.o..o...', '..oo....', '.o..o.o.', '.o...o..', '..ooo.o.', '........')),
    array('code'=> 0x167, 'patterns' => array( '.....o..', '....o...', '...o....', '........', '........', '........', '........', '........')),
    array('code'=> 0x168, 'patterns' => array( '.....o..', '....o...', '...o....', '...o....', '...o....', '....o...', '.....o..', '........')),
    array('code'=> 0x169, 'patterns' => array( '..o.....', '...o....', '....o...', '....o...', '....o...', '...o....', '..o.....', '........')),
    array('code'=> 0x16a, 'patterns' => array( '........', '....o...', '....o...', '..ooooo.', '....o...', '....o...', '........', '........')),
    array('code'=> 0x16b, 'patterns' => array( '....o...', '..o.o.o.', '...ooo..', '..ooooo.', '...ooo..', '..o.o.o.', '....o...', '........')),
    array('code'=> 0x16c, 'patterns' => array( '....oooo', '....oooo', '....oooo', '....oooo', 'oooo....', 'oooo....', 'oooo....', 'oooo....')),
    array('code'=> 0x16d, 'patterns' => array( 'o......o', '.o....o.', '..o..o..', '...oo...', '...oo...', '..o..o..', '.o....o.', 'o......o')),
    array('code'=> 0x16e, 'patterns' => array( '...o....', '...o....', '..o.....', 'oo......', '........', '........', '........', '........')),
    array('code'=> 0x16f, 'patterns' => array( '....o...', '....o...', '.....o..', '......oo', '........', '........', '........', '........')),
    array('code'=> 0x170, 'patterns' => array( 'oooooooo', '........', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x171, 'patterns' => array( 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......')),
    array('code'=> 0x172, 'patterns' => array( 'oooooooo', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......', 'o.......')),
    array('code'=> 0x173, 'patterns' => array( 'oooooooo', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o', '.......o')),
    array('code'=> 0x174, 'patterns' => array( '........', '........', 'oooooooo', '........', '........', '........', '........', '........')),
    array('code'=> 0x175, 'patterns' => array( '..o.....', '..o.....', '..o.....', '..o.....', '..o.....', '..o.....', '..o.....', '..o.....')),
    array('code'=> 0x176, 'patterns' => array( '.....o..', '....o...', '...o...o', '..o...o.', '.o...o..', 'o...o...', '...o....', '..o.....')),
    array('code'=> 0x177, 'patterns' => array( '..o.....', '...o....', 'o...o...', '.o...o..', '..o...o.', '...o...o', '....o...', '.....o..')),
    array('code'=> 0x178, 'patterns' => array( '........', '........', '........', '........', 'oooooooo', '........', '........', '........')),
    array('code'=> 0x179, 'patterns' => array( '....o...', '....o...', '....o...', '....o...', '....o...', '....o...', '....o...', '....o...')),
    array('code'=> 0x17a, 'patterns' => array( 'oooooooo', 'oooooooo', 'oooooooo', 'oooooooo', '........', '........', '........', '........')),
    array('code'=> 0x17b, 'patterns' => array( 'oooo....', 'oooo....', 'oooo....', 'oooo....', 'oooo....', 'oooo....', 'oooo....', 'oooo....')),
    array('code'=> 0x17c, 'patterns' => array( '........', '........', '........', '........', '........', '........', 'oooooooo', '........')),
    array('code'=> 0x17d, 'patterns' => array( '......o.', '......o.', '......o.', '......o.', '......o.', '......o.', '......o.', '......o.')),
    array('code'=> 0x17e, 'patterns' => array( '........', '........', '........', '........', '........', 'oooooooo', 'oooooooo', 'oooooooo')),
    array('code'=> 0x17f, 'patterns' => array( '.....ooo', '.....ooo', '.....ooo', '.....ooo', '.....ooo', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x180, 'patterns' => array( '........', '....o...', '....o...', '....o...', '..o.o.o.', '...ooo..', '....o...', '........')),
    array('code'=> 0x181, 'patterns' => array( '...o....', 'ooooooo.', '..o.....', '.ooooo..', '......o.', '......o.', 'oooooo..', '........')),
    array('code'=> 0x182, 'patterns' => array( '........', 'oooooo..', '......o.', '........', '........', 'o.......', '.oooooo.', '........')),
    array('code'=> 0x183, 'patterns' => array( '..oooo..', '....o...', '...o....', '.oooooo.', '....o...', '...o....', '....oo..', '........')),
    array('code'=> 0x184, 'patterns' => array( '.o......', '.o......', '.o......', '.o......', '.o...o..', '.o...o..', '..ooo...', '........')),
    array('code'=> 0x185, 'patterns' => array( 'o....o..', 'o.....o.', 'o.....o.', 'o.....o.', 'o.....o.', 'o..o....', '.oo.....', '........')),
    array('code'=> 0x186, 'patterns' => array( 'o....o..', 'o..oooo.', 'o....o..', 'o....o..', 'o..ooo..', 'o.o..oo.', '.o.ooo..', '........')),
    array('code'=> 0x187, 'patterns' => array( '...o....', '.oooooo.', '....o...', '.oooooo.', '.....o..', '......o.', '.oo.....', '...oo...')),
    array('code'=> 0x188, 'patterns' => array( '....oo..', '...oo...', '..oo....', '.oo.....', '..oo....', '...oo...', '....oo..', '........')),
    array('code'=> 0x189, 'patterns' => array( 'o..oooo.', 'o.......', 'o.......', 'o.......', 'o.......', 'o..o....', 'oo.oooo.', '........')),
    array('code'=> 0x18a, 'patterns' => array( '...o....', '.oooooo.', '...o....', '.oooooo.', '...o....', '.ooo....', 'o..ooo..', '.ooo..o.')),
    array('code'=> 0x18b, 'patterns' => array( '..ooo...', '.o.o.o..', 'o..o..o.', 'o..o..o.', 'o..o..o.', 'o..o..o.', '.oo..o..', '........')),
    array('code'=> 0x18c, 'patterns' => array( '.o...o..', '.o...o..', '.o...o..', '.oo..o..', '.....o..', '....o...', '...o....', '........')),
    array('code'=> 0x18d, 'patterns' => array( '..o.....', 'ooooo...', '..o.....', 'ooooo...', '..o...o.', '..o...o.', '...ooo..', '........')),
    array('code'=> 0x18e, 'patterns' => array( '.ooo....', '...o....', '...o.o..', '.oooooo.', 'o..o.o..', 'o..o.o..', '.oo..o..', '........')),
    array('code'=> 0x18f, 'patterns' => array( '.oo.....', '........', 'o..ooo..', 'o.o...o.', 'oo....o.', 'o.....o.', '...ooo..', '........')),
    array('code'=> 0x190, 'patterns' => array( '.o...o..', '.o...o..', 'ooooooo.', '.o...o..', '.o.oo...', '.o......', '..ooooo.', '........')),
    array('code'=> 0x191, 'patterns' => array( '..o.....', 'oooooo..', '.o......', '.o.oooo.', 'o.......', 'o.o.....', 'o.ooooo.', '........')),
    array('code'=> 0x192, 'patterns' => array( '....o...', 'ooooooo.', '....o...', '..ooo...', '.o..o...', '..ooo...', '....o...', '...o....')),
    array('code'=> 0x193, 'patterns' => array( '..o.....', '..o...o.', '..o.oo..', '..oo....', '.o......', 'o.......', '.oooooo.', '........')),
    array('code'=> 0x194, 'patterns' => array( '..o...o.', 'ooooo..o', '..o..o.o', '..o..o..', '..o..o..', '..o..o..', '.o..o...', '........')),
    array('code'=> 0x195, 'patterns' => array( '..o.....', 'ooooo.o.', '.o.....o', '.o...o..', 'o..ooo..', 'o.o..oo.', '...ooo..', '........')),
    array('code'=> 0x196, 'patterns' => array( 'ooo.....', '..o..oo.', '.o...o.o', 'o....o..', 'o....o..', 'o...o...', '.ooo....', '........')),
    array('code'=> 0x197, 'patterns' => array( 'ooooooo.', '.....o..', '....o...', '...o....', '...o....', '....o...', '.....o..', '........')),
    array('code'=> 0x198, 'patterns' => array( '..o.....', 'ooooooo.', '...o....', '....o...', '.o...o..', '..o.....', '...oo...', '........')),
    array('code'=> 0x199, 'patterns' => array( '...o....', '..o.....', '..o.....', '.ooo....', '.o..o...', 'o...o...', 'o....oo.', '........')),
    array('code'=> 0x19a, 'patterns' => array( 'o.......', '.ooooo..', '......o.', '......o.', '......o.', '.....o..', '...oo...', '........')),
    array('code'=> 0x19b, 'patterns' => array( '.ooooo..', '....o...', '...o....', '..o.oo..', '.o....o.', '......o.', '..o..o..', '...oo...')),
    array('code'=> 0x19c, 'patterns' => array( 'o....o..', 'o.ooooo.', 'o....o..', 'o....o..', 'o....o..', 'o....o..', '.o..o...', '........')),
    array('code'=> 0x19d, 'patterns' => array( '...oooo.', '...o....', '...o....', '...o....', '........', '........', '........', '........')),
    array('code'=> 0x19e, 'patterns' => array( '........', '..o.....', '.ooo....', '..o.....', '.oooo...', 'o..o.o..', '.oo.o...', '........')),
    array('code'=> 0x19f, 'patterns' => array( '........', '........', '.o.oo...', 'ooo..o..', '..o.o...', '..o.....', '...o....', '........')),
    array('code'=> 0x1a0, 'patterns' => array( '..o.....', 'ooo..o..', '..o.o.o.', '..oo..o.', '.oo...o.', 'o.o...o.', '..o..o..', '........')),
    array('code'=> 0x1a1, 'patterns' => array( '.....o..', '.o...o..', '.ooooo..', '.o..o.o.', 'o.oo..o.', 'o..o.ooo', '.oo..oo.', '........')),
    array('code'=> 0x1a2, 'patterns' => array( '..ooo...', '........', '...o....', '.o..o.o.', '.o..o.o.', 'o...o.o.', '..oo....', '........')),
    array('code'=> 0x1a3, 'patterns' => array( '..o.....', 'oooooo..', '..o.....', '.ooooo..', 'o.o.o.o.', 'o..o..o.', '.oo..o..', '........')),
    array('code'=> 0x1a4, 'patterns' => array( '...oo...', '........', '..oooo..', '.o....o.', '......o.', '.....o..', '....o...', '........')),
    array('code'=> 0x1a5, 'patterns' => array( '...o....', '........', '.ooooo..', '....o...', '...o....', '..o.o...', '.o...oo.', '........')),
    array('code'=> 0x1a6, 'patterns' => array( '..o.....', 'oooooo.o', '..o....o', '.ooooo..', 'o.o...o.', 'o.o...o.', '.oo..o..', '........')),
    array('code'=> 0x1a7, 'patterns' => array( '.o..o...', '.o..oo..', '..oo..o.', 'ooo...o.', '..o..o..', '...o....', '...o....', '....o...')),
    array('code'=> 0x1a8, 'patterns' => array( '....o...', 'o..ooo..', 'o.o.o.o.', 'oo..o.o.', 'oo..o.o.', 'o...oo..', '...oo...', '........')),
    array('code'=> 0x1a9, 'patterns' => array( '....o...', '....ooo.', '....o...', '....o...', '.oooo...', 'o...ooo.', '.oooo...', '........')),
    array('code'=> 0x1aa, 'patterns' => array( 'o..oooo.', 'o....o..', 'o..oooo.', 'o....o..', 'o..ooo..', 'o.o..oo.', 'oo.ooo..', '........')),
    array('code'=> 0x1ab, 'patterns' => array( '........', '..o.....', '.o.o....', 'o...o...', '.....o..', '......o.', '......o.', '........')),
    array('code'=> 0x1ac, 'patterns' => array( '..o.....', 'ooo..oo.', '..o.oo..', '..oo.o..', '.oo..o..', 'o.o..o..', '..o...o.', '........')),
    array('code'=> 0x1ad, 'patterns' => array( '.....o..', '.o...o..', '.ooooo..', '.o..o.o.', 'o.oo..o.', 'o..o..o.', '.oo..o..', '........')),
    array('code'=> 0x1ae, 'patterns' => array( '.ooooo..', '....o...', '...o....', '..oooo..', '.o....o.', '...oo.o.', '..o..o..', '...oo...')),
    array('code'=> 0x1af, 'patterns' => array( '..o.....', 'ooo..o..', '..o.o.o.', '..oo..o.', '.oo..oo.', 'o.o.o.oo', '..o..oo.', '........')),
    array('code'=> 0x1b0, 'patterns' => array( '..o.....', 'oooooo.o', '..o....o', '.oo.....', 'o.o.....', '.oo...o.', '..ooooo.', '........')),
    array('code'=> 0x1b1, 'patterns' => array( '........', '........', '........', '........', '....o...', '....o...', '....o...', '.oooo...')),
    array('code'=> 0x1b2, 'patterns' => array( '........', '........', '.o..o...', '.o...o..', '.o...o..', '.o...o..', '..o.....', '........')),
    array('code'=> 0x1b3, 'patterns' => array( '........', '........', '...o....', 'o.ooo...', 'oo.o.o..', 'o..oo...', '..oo....', '........')),
    array('code'=> 0x1b4, 'patterns' => array( '...o....', 'ooooooo.', '..o.....', '.ooo.o..', 'o.ooo...', '.o..o...', '.oooooo.', '........')),
    array('code'=> 0x1b5, 'patterns' => array( '........', '........', '........', '........', '........', '.o......', '..o.....', '...o....')),
    array('code'=> 0x1b6, 'patterns' => array( '........', '..o.....', '........', '.oooo...', '.....o..', '.....o..', '....o...', '........')),
    array('code'=> 0x1b7, 'patterns' => array( '........', '........', '..o.....', '..ooo...', '..o.....', '.oooo...', '.oo.....', '........')),
    array('code'=> 0x1b8, 'patterns' => array( '.ooo....', '.o.o....', '.ooo....', '........', '........', '........', '........', '........')),
    array('code'=> 0x1b9, 'patterns' => array( '........', '........', '........', '........', '........', '........', '..o.....', '........')),
    array('code'=> 0x1ba, 'patterns' => array( '........', '..o.....', '........', '.oooo...', '...o....', '..oo....', '.o..oo..', '........')),
    array('code'=> 0x1bb, 'patterns' => array( '........', '........', '........', 'ooooo...', '.....o..', '.....o..', '...oo...', '........')),
    array('code'=> 0x1bc, 'patterns' => array( '..o.....', 'o..o....', '.o......', '........', '........', '........', '........', '........')),
    array('code'=> 0x1bd, 'patterns' => array( '........', '........', '........', '........', '........', '.ooo....', '.o.o....', '.ooo....')),
    array('code'=> 0x1be, 'patterns' => array( '........', '..o.....', '.ooo.o..', '..o.....', '.oooo...', 'o.o..o..', '.oo.o...', '........')),
    array('code'=> 0x1bf, 'patterns' => array( '........', '........', '........', '...ooo..', '........', '........', '........', '........')),
    array('code'=> 0x1c0, 'patterns' => array( '...ooo..', '...ooo..', '..ooooo.', '...ooo..', '....o...', '........', '..ooooo.', '........')),
    array('code'=> 0x1c1, 'patterns' => array( 'oooooooo', 'oooo.ooo', 'oooo.ooo', 'oooo.ooo', 'oo.o.o.o', 'ooo...oo', 'oooo.ooo', 'oooooooo')),
    array('code'=> 0x1c2, 'patterns' => array( 'oooooooo', 'oooo.ooo', 'ooo...oo', 'oo.o.o.o', 'oooo.ooo', 'oooo.ooo', 'oooo.ooo', 'oooooooo')),
    array('code'=> 0x1c3, 'patterns' => array( 'oooooooo', 'oooooooo', 'oooo.ooo', 'ooooo.oo', 'o......o', 'ooooo.oo', 'oooo.ooo', 'oooooooo')),
    array('code'=> 0x1c4, 'patterns' => array( 'oooooooo', 'oooooooo', 'ooo.oooo', 'oo.ooooo', 'o......o', 'oo.ooooo', 'ooo.oooo', 'oooooooo')),
    array('code'=> 0x1c5, 'patterns' => array( 'o.ooo.oo', 'o.ooo.oo', 'o.ooo.oo', 'o.....oo', 'o.ooo.oo', 'o.ooo.oo', 'o.ooo.oo', 'oooooooo')),
    array('code'=> 0x1c6, 'patterns' => array( 'ooo...oo', 'oo.ooo.o', 'o.oooooo', 'o.oooooo', 'o.oooooo', 'oo.ooo.o', 'ooo...oo', 'oooooooo')),
    array('code'=> 0x1c7, 'patterns' => array( '...oo...', '..o..o..', '.oooooo.', 'oooooooo', '.o.oo.o.', '..o..o..', '........', '........')),
    array('code'=> 0x1c8, 'patterns' => array( 'ooo.....', '.o...ooo', '.o....o.', '.oooooo.', '.o....o.', '.o...ooo', 'ooo.....', '........')),
    array('code'=> 0x1c9, 'patterns' => array( '..o...o.', '..ooooo.', '..o.o.o.', '....o...', '....o...', '.o..o..o', '.ooooooo', '.o.....o')),
    array('code'=> 0x1ca, 'patterns' => array( '...ooo..', '...ooo..', '....o...', '..ooooo.', '....o...', '....o...', '...o.o..', '..o...o.')),
    array('code'=> 0x1cb, 'patterns' => array( '........', '...o...o', 'oo.o..o.', 'oooooo..', 'oo.o..o.', '...o...o', '........', '........')),
    array('code'=> 0x1cc, 'patterns' => array( '........', 'o...o...', '.o..o.oo', '..oooooo', '.o..o.oo', 'o...o...', '........', '........')),
    array('code'=> 0x1cd, 'patterns' => array( '..o...o.', '...o.o..', '....o...', '....o...', '..ooooo.', '....o...', '...ooo..', '...ooo..')),
    array('code'=> 0x1ce, 'patterns' => array( '..oooo..', '.oooooo.', 'oooooooo', 'oo.oo.oo', 'oooooooo', 'ooo..ooo', '.oooooo.', '..oooo..')),
    array('code'=> 0x1cf, 'patterns' => array( '..oooo..', '.o....o.', 'o......o', 'o.o..o.o', 'o......o', 'o..oo..o', '.o....o.', '..oooo..')),
    array('code'=> 0x1d0, 'patterns' => array( '..ooooo.', '..o...o.', '..o...o.', '..ooooo.', '..o...o.', '..o...o.', '..ooooo.', '........')),
    array('code'=> 0x1d1, 'patterns' => array( '..ooooo.', '..o...o.', '..ooooo.', '..o...o.', '..ooooo.', '..o...o.', '.o....o.', '........')),
    array('code'=> 0x1d2, 'patterns' => array( '....o...', '..o.o.o.', '..o.o.o.', '....o...', '...o.o..', '..o...o.', '.o.....o', '........')),
    array('code'=> 0x1d3, 'patterns' => array( '....o...', '....o..o', '..ooo.o.', '....oo..', '...ooo..', '..o.o.o.', '.o..o..o', '........')),
    array('code'=> 0x1d4, 'patterns' => array( '....o...', '....o...', '..ooooo.', '....o...', '...ooo..', '..o.o.o.', '.o..o..o', '........')),
    array('code'=> 0x1d5, 'patterns' => array( '....o...', '...o.o..', '..ooooo.', '.o..o..o', '..ooooo.', '...ooo..', '.ooooooo', '........')),
    array('code'=> 0x1d6, 'patterns' => array( '........', '....o...', '....o...', '..ooooo.', '....o...', '....o...', '.ooooooo', '........')),
    array('code'=> 0x1d7, 'patterns' => array( '....o...', '.o..o...', '.oooooo.', '.o..o...', '..ooooo.', '....o...', '.ooooooo', '........')),
    array('code'=> 0x1d8, 'patterns' => array( '..o.....', '..ooooo.', '.o..o...', '..oooo..', '..o.o...', '.oooooo.', '....o...', '........')),
    array('code'=> 0x1d9, 'patterns' => array( '.....o..', '.oooooo.', '.o.o.o..', '.ooooooo', '.o.o..o.', '.ooooooo', '....o.o.', '........')),
    array('code'=> 0x1da, 'patterns' => array( '....o...', '...o.o..', '..o...o.', '.ooooooo', '...o..o.', '...o..o.', '..o..o..', '........')),
    array('code'=> 0x1db, 'patterns' => array( '..ooo...', '...o..o.', '.ooooooo', '...o.ooo', '..ooo.oo', '.o.o..o.', '...o.o..', '........')),
    array('code'=> 0x1dc, 'patterns' => array( '.ooooooo', '.o..o..o', '.o..o..o', '.ooooooo', '.o.....o', '.o.....o', '.o.....o', '........')),
    array('code'=> 0x1dd, 'patterns' => array( '..o...o.', '...o.o..', '..ooooo.', '....o...', '..ooooo.', '....o...', '....o...', '........')),
    array('code'=> 0x1de, 'patterns' => array( '....oo..', '...o..o.', '...o....', '..ooo...', '...o....', '...o....', '..ooooo.', '........')),
    array('code'=> 0x1df, 'patterns' => array( '........', 'oo......', 'oo..o...', '.o.o.o..', '.o.o.o..', '.o.o.o.o', '..o...o.', '........')),
    array('code'=> 0x1e0, 'patterns' => array( '........', '........', '........', '........', '........', '......o.', 'oooooooo', '......o.')),
    array('code'=> 0x1e1, 'patterns' => array( '......o.', '......o.', '......o.', '......o.', '......o.', '......o.', '.....ooo', '......o.')),
    array('code'=> 0x1e2, 'patterns' => array( '......o.', '......o.', '......o.', '......o.', '......o.', '......o.', 'oooooooo', '......o.')),
    array('code'=> 0x1e3, 'patterns' => array( '........', '........', '..o.....', '.o.o....', 'o...o...', '.....o.o', '......o.', '........')),
    array('code'=> 0x1e4, 'patterns' => array( '........', '....ooo.', '...o...o', '..o...o.', 'oo...o..', '.....o..', '......o.', '.......o')),
    array('code'=> 0x1e5, 'patterns' => array( '........', 'oooooooo', '........', 'o......o', '.o....o.', '.o....o.', 'o......o', '........')),
    array('code'=> 0x1e6, 'patterns' => array( '........', '.ooo....', 'o...o...', '.o...o..', '..o...oo', '..o.....', '.o......', 'o.......')),
    array('code'=> 0x1e7, 'patterns' => array( '........', 'oo...o..', 'o.o..o..', 'o..o.o..', 'o...oooo', 'o..o.o..', 'o.o..o..', 'oo...o..')),
    array('code'=> 0x1e8, 'patterns' => array( '........', '..o...oo', '..o..o.o', '..o.o..o', 'oooo...o', '..o.o..o', '..o..o.o', '..o...oo')),
    array('code'=> 0x1e9, 'patterns' => array( 'o...o...', 'o..o....', 'o.o.....', 'oo......', 'oo......', 'o.o.o...', 'o..oo...', 'o.ooo...')),
    array('code'=> 0x1ea, 'patterns' => array( 'o.o.o...', 'o.oo....', 'o.ooo...', 'oo......', 'oo......', 'o.o.....', 'o..o....', 'o...o...')),
    array('code'=> 0x1eb, 'patterns' => array( 'o.......', '.o......', '..o.....', '...o....', '...ooooo', '..o.....', '.o......', 'o.......')),
    array('code'=> 0x1ec, 'patterns' => array( '........', '........', '..o..o..', '..o..o..', 'ooo..ooo', '..o..o..', '..o..o..', '........')),
    array('code'=> 0x1ed, 'patterns' => array( '....o...', '....o...', '..ooooo.', '........', '........', '..ooooo.', '....o...', '....o...')),
    array('code'=> 0x1ee, 'patterns' => array( '....o...', '...o....', '..o.....', '...o....', '....o...', '.....o..', '......o.', '.....o..')),
    array('code'=> 0x1ef, 'patterns' => array( '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.', '.o.o.o.o', 'o.o.o.o.')),
    array('code'=> 0x1f0, 'patterns' => array( '........', '........', '........', '........', '........', '........', '........', '........')),
    array('code'=> 0x1f1, 'patterns' => array( '........', '.ooo....', '.ooo....', '.ooo....', '........', '........', '........', '........')),
    array('code'=> 0x1f2, 'patterns' => array( '........', '.....ooo', '.....ooo', '.....ooo', '........', '........', '........', '........')),
    array('code'=> 0x1f3, 'patterns' => array( '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo', '........', '........', '........', '........')),
    array('code'=> 0x1f4, 'patterns' => array( '........', '........', '........', '........', '........', '.ooo....', '.ooo....', '.ooo....')),
    array('code'=> 0x1f5, 'patterns' => array( '........', '.ooo....', '.ooo....', '.ooo....', '........', '.ooo....', '.ooo....', '.ooo....')),
    array('code'=> 0x1f6, 'patterns' => array( '........', '.....ooo', '.....ooo', '.....ooo', '........', '.ooo....', '.ooo....', '.ooo....')),
    array('code'=> 0x1f7, 'patterns' => array( '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo', '........', '.ooo....', '.ooo....', '.ooo....')),
    array('code'=> 0x1f8, 'patterns' => array( '........', '........', '........', '........', '........', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x1f9, 'patterns' => array( '........', '.ooo....', '.ooo....', '.ooo....', '........', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x1fa, 'patterns' => array( '........', '.....ooo', '.....ooo', '.....ooo', '........', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x1fb, 'patterns' => array( '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo', '........', '.....ooo', '.....ooo', '.....ooo')),
    array('code'=> 0x1fc, 'patterns' => array( '........', '........', '........', '........', '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo')),
    array('code'=> 0x1fd, 'patterns' => array( '........', '.ooo....', '.ooo....', '.ooo....', '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo')),
    array('code'=> 0x1fe, 'patterns' => array( '........', '.....ooo', '.....ooo', '.....ooo', '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo')),
    array('code'=> 0x1ff, 'patterns' => array( '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo', '........', '.ooo.ooo', '.ooo.ooo', '.ooo.ooo'))
);
$basecolors = array(
        array(0x00, 0x00, 0x00),
        array(0x00, 0x00, 0xff),
        array(0xff, 0x00, 0x00),
        array(0xff, 0x00, 0xff),
        array(0x00, 0xff, 0x00),
        array(0x00, 0xff, 0xff),
        array(0xff, 0xff, 0x00),
        array(0xff, 0xff, 0xff)
);

header('Content-type: text/plain; charset=utf-8');

foreach($MZ700FON as $f) {
    for($bidx = 0; $bidx < 8; $bidx++) {
        for($fidx = 0; $fidx < 8; $fidx++) {

            // filename
            $attr = $fidx * 16 + $bidx + ($f['code'] > 0xff ? 0x80 : 0);
            $attr = strtoupper(dechex($attr));
            if(strlen($attr) < 2) {
                $attr = '0' . $attr;
            }
            $dispcode = $f['code'] & 0xff;
            $dispcode = strtoupper(dechex($dispcode));
            if(strlen($dispcode) < 2) {
                $dispcode = '0' . $dispcode;
            }
            $fname = './MZ700FON/' . $attr . $dispcode . '.png';

            // Remove files that have lower alphabet in its filename
            if(/[a-f]/.test($attr.$dispcode)) {
                $rm_fname = './MZ700FON/' . strtolower($attr . $dispcode) . '.png';
                if(file_exists($rm_fname)) {
                    unlink($rm_fname);
                    echo("rm " . $rm_fname ."\r\n");
                }
            }
            // Skip creation, if the file already exists
            if(file_exists($fname)) {
                continue;
            }
            // create image
            $img = imagecreatetruecolor(8, 8);

            // draw background
            $brgb = $basecolors[$bidx];
            $bgc = imagecolorallocate($img, $brgb[0], $brgb[1], $brgb[2]);
                
            // draw glyph
            $frgb = $basecolors[$fidx];
            $fgc = imagecolorallocate($img, $frgb[0], $frgb[1], $frgb[2]);
            imagefilledrectangle($img, 0,0,7,7, $bgc);
            for($y = 0; $y < 8; $y++) {
                for($x = 0; $x < 8; $x++) {
                    if($f['patterns'][$y]{$x} == 'o') {
                        imagefilledrectangle($img, $x,$y,$x,$y, $fgc);
                    }
                }
            }

            // output
            imagepng($img, $fname);
            echo("create " . $fname ."\r\n");

            //destroy image
            imagedestroy($img);
        }
    }
}
echo("ok.\r\n");
